
course: "CS190J"
legacy_wiki_name: 8wiki
legacy_wiki_url:  
qtr: "W18"
quarter: "Winter 2018"
ta_list: ""
ta_list_full: ""
instructor: "Conrad and Mirza"
piazza: https://piazza.com/class/jcdqu3kt8l9276

github_url: https://github.com/ucsb-cs190j-w18/ucsb-cs190j-w18.github.io
course_site:

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048



legacy_wiki_url: https://foo.cs.ucsb.edu/8wiki
legacy_wiki_name: "8wiki"


start_week: 1
start_date: 2018-01-14 00:00:00.00-8:00
num_weeks: 9
extra_exam_week: true

instructor_url: https://ucsb-cs16.github.io/instructor

cal_dates: >
  [
  {"label":"First day of classes", "date":"2018-01-16" },
  {"label":"Last day to Add","date":"2018-01-22" },
  {"label":"Last day to Add with code","date":"2018-02-05" },
  {"label":"Drop Deadline (no W grade)","date":"2017-02-12" },
  {"label":"Univ Holiday: Martin Luther King Day", "date":"2018-01-15" },
  {"label":"Univ Holiday: Presidents Day", "date":"2018-02-19" },
  {"label":"Last day of classes", "date":"2018-03-16" },            
  ]




kramdown:
   parse_block_html: true
   default_lang: python


exclude:
   - vendor


timezone: America/Los_Angeles

collections:
  papers:
    output: true
    permalink: /hwk/:path/
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  teams:
    output: true
    permalink: /teams/:path/
  lectures:
    output: true
    permalink: /lectures/:path/



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: teams
    values:
      layout: teams
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout


